### ISSUE TITLE
Styles affect other inputs

### ISSUE THREAD

**Issue by daun** [juergenweb/FieldtypeOpeningHours#4]
Just a quick note that this CSS here isn't scoped to the module and changes the background color on unrelated inputs on the same page. I commented out the section and it works fine, but I wasn't sure what your intentions were with it.

```css
.Inputfields input:not([type="submit"]):not([type="file"]):not([type="checkbox"]):not([type="radio"]):not(.uk-form-blank), .Inputfields textarea:not(.uk-form-blank) {
  background: #fff;
}
```
